services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./work:/home/jovyan/work
      - ./requirements.txt:/tmp/requirements.txt
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
    env_file:
      - .env
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-""}
      - DOCKER_STACKS_JUPYTER_CMD=${DOCKER_STACKS_JUPYTER_CMD:-"lab"}
    command: >
      start-notebook.py
      --NotebookApp.token='${JUPYTER_TOKEN}'